version: "{build}"
shallow_clone: true
clone_folder: c:\gopath\src\github.com\sourcegraph\cloneproxy
environment:
  GOPATH: c:\gopath
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v golang.org/x/tools/cmd/goimports
build_script:
  - goimports -d *.go
  - go test -v ./...